linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - nonamedreturns
    - testpackage
    - exhaustruct
    - exhaustive
    - varnamelen
    - forbidigo
    - gofumpt
    - gci
    # deprecated :(
    - exhaustivestruct
    - interfacer
    - scopelint
    - maligned
    - golint
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: pkg/client/http.go
      text: "G402" # G402: TLS InsecureSkipVerify set true.
      linters:
        - gosec
    - path: ._test\.go
      linters:
        - funlen
        - ifshort
        - cyclop
        - dupl
        - goerr113
        - errcheck
