# .goreleaser.yml
project_name: crawley
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "crawley"
    dir: .
    main: ./cmd/crawley
